### PR TITLE
Implemented Project_Euler_1 Multiple_Of_3_And_5 in C

### PR DESCRIPTION
**Pull request by SanjayMarreddi**
## Assigned Issue Number?
#126 

## Language Opted?
C

## Number of files added or updated?
1

## Name of these files?
 Project_Euler => 1-Multiple_Of_3_And_5 =>1-Multiple_Of_3_And_5.c

example :
Algorithms => Searching => Linear_Search => Linear_Search.py

### Checklist

- [x] I was assigned for this otherwise my **PR will be rejected**.
- [x] I've read the contribution guidelines.
- [x] I've referred the correct issue number.
- [x] I've filled up this entire template correctly.

:star2: this repository and support.

### CODE REVIEW

**Comment by SanjayMarreddi** [comment]
@krishrahul98 Could you review this ?

**Review by krishrahul98 — APPROVED** [review]
👍 Great @SanjayMarreddi

**Comment by krishrahul98** [comment]
@SanjayMarreddi  are you implementing other 4 too or just this one?

**Comment by SanjayMarreddi** [comment]
@krishrahul98  I will implement the other 4 too !

**Comment by krishrahul98** [comment]
> @krishrahul98 I will implement the other 4 too !

Great @SanjayMarreddi

**Pull request merged**
