### PR TITLE
Added 3 

### PR DESCRIPTION
**Pull request by AayushTyagi1**
## Name of these files?
main folder => sub_folder => ... => ... =>  file.py
DSA-Library => Data_Structures => LinkedList => Middle element linked list => mid_in_LL.c
DSA-Library => Data_Structures => LinkedList => Queue using Linked List => queue_using_LL.c

Checklist
 I was assigned for this otherwise my PR will be rejected.
 I've read the contribution guidelines.
 I've referred the correct issue number.
 I've filled up this entire template correctly.
🌟 this repository and support.

### CODE REVIEW

**Comment by AayushTyagi1** [comment]
I have added 3 programs

**Comment by krishrahul98** [comment]
@AayushTyagi1 Fill PR template correctly and and write issue number where you were assigned.

**Comment by krishrahul98** [comment]
Fill template like this one
https://github.com/krishrahul98/DSA-Library/pull/148

**Comment by AayushTyagi1** [comment]
> Fill template like this one
> #148

Is this correct now?

**Comment by krishrahul98** [comment]
> > Fill template like this one
> > #148
> 
> Is this correct now?

Ok I am accepting your PR. But you werw not assigned to these problems. 
First get assigned by raising issue then PR. That's the way of open source.

**Review by krishrahul98 — COMMENTED** [review]
Great work

**Pull request merged**
