### PR TITLE
Create search_in_sorted_rotated_array.java

### PR DESCRIPTION
**Pull request by AnkitaM84**
## Assigned Issue Number?
#43 

## Language Opted?
Java

## Number of files added or updated?
1

## Name of these files?
Data_Structures => Array => search_in_sorted_rotated_array.java

### Checklist

- [x] I was assigned for this otherwise my **PR will be rejected**.
- [x] I've read the contribution guidelines.
- [x] I've referred the correct issue number.
- [x] I've filled up this entire template correctly.

:star2: this repository and support.

### CODE REVIEW

**Review by krishrahul98 — APPROVED** [review]
@AnkitaM84 👍

**Comment by AnkitaM84** [comment]
@krishrahul98 could you please add hacktoberfest accepted tag? It would help a lot.
Thank you so much.

**Comment by krishrahul98** [comment]
@AnkitaM84 I have added hacktoberfest in topic. So, no need to add specific hacktoberfest-accepted in PR everytime.
You can in hacktoberfest it will be showing as accepted.

**Comment by AnkitaM84** [comment]
Oh, yes. thanks :)

**Review by krishrahul98 — COMMENTED** [review]
👍🏼

**Pull request merged**
