### PR TITLE
Queue implementation in java

### PR DESCRIPTION
**Pull request by BraveeSnow**
## Assigned Issue Number?
#064

## Language Opted?
Java

## Number of files added or updated?
1

## Name of these files?
Data_Structures => Queue => Queue_Implementation.java

example :
Algorithms => Searching => Linear_Search => Linear_Search.py

### Checklist

- [x] I was assigned for this otherwise my **PR will be rejected**.
- [x] I've read the contribution guidelines.
- [x] I've referred the correct issue number.
- [x] I've filled up this entire template correctly.

### CODE REVIEW

**Comment by BraveeSnow** [comment]
I did see another java implementation in the 'Implementations' folder. Just wanted to let you know that I actually did ask to write the queue implementation in java ([here](https://github.com/krishrahul98/DSA-Library/issues/64#issuecomment-705974426)).

**Comment by krishrahul98** [comment]
@BraveeSnow Don't Worry. I will add this as another implementation. 👍🏼

**Comment by BraveeSnow** [comment]
Okay, thanks!

**Review by krishrahul98 — COMMENTED** [review]
👍🏼

**Pull request merged**
