### PR TITLE
Create circular queue using reference

### PR DESCRIPTION
**Pull request by avniagarwal23**
## Assigned Issue Number?
#001

## Language Opted?
C/C++/Python/Java/...

## Number of files added or updated?
1/2/3

## Name of these files?
main folder => sub_folder => ... => ... =>  file.py

example :
Algorithms => Searching => Linear_Search => Linear_Search.py

### Checklist

- [ ] I was assigned for this otherwise my **PR will be rejected**.
- [ ] I've read the contribution guidelines.
- [ ] I've written code by myself. **No Plagiarism allowed**
- [ ] I've referred the correct issue number.
- [ ] I've filled up this entire template correctly.

:star2: this repository and support.

### CODE REVIEW

**Comment by Taz03** [comment]
this is spam pr for the hacktoberfest event pls tag this as spam

**Comment by krishrahul98** [comment]
@avniagarwal23 Merged 👍🏼

**Comment by avniagarwal23** [comment]
thank uuu🙂🙂

**Comment by Taz03** [comment]
dafuq y, this is not even a proper file theres no file format. u guys are really onto something

spammers

**Comment by krishrahul98** [comment]
> dafuq y, this is not even a proper file theres no file format. u guys are really onto something
> 
> spammers

@Taz03 Thanks for pointing it out. I was busy and didn't check file-format. I have fixed this issue.

**Comment by Taz03** [comment]
@krishrahul98 no u haven't mark this pr as spam, we are the one responsible to make this a fair event dont make it a tshirt grind fest idk y @avniagarwal23 is so greedy for this tshirt tho

**Comment by Taz03** [comment]
also marking it as spam will get them banned from the event

**Pull request merged**
