### PR TITLE
Create BucketSort.java

### PR DESCRIPTION
**Pull request by Priyanshi-3**
This sorts the input values, which are uniformly distributed over a range, using bucket sort algorithm. The input values are placed in buckets and the values in each bucket are sorted using inbuilt sort function of Collections framework.

## Assigned Issue Number?
#001

## Language Opted?
C/C++/Python/Java/...

## Number of files added or updated?
1/2/3

## Name of these files?
main folder => sub_folder => ... => ... =>  file.py

example :
Algorithms => Searching => Linear_Search => Linear_Search.py

### Checklist

- [x] I was assigned for this otherwise my **PR will be rejected**.
- [x] I've read the contribution guidelines.
- [x] I've referred the correct issue number.
- [x] I've filled up this entire template correctly.

:star2: this repository and support.

### CODE REVIEW

**Review by krishrahul98 — APPROVED** [review]
👍

**Comment by Priyanshi-3** [comment]
Thank you for merging my PR. Please add hacktoberfest-accepted label to the PR#103

**Comment by krishrahul98** [comment]
> Thank you for merging my PR. Please add hacktoberfest-accepted label to the PR #103

@Priyanshi-3 
This repository has hacktoberfest added in topic. So, no need to add to hactoberfest-accepted label to every PR. you can check in your hacktoberfest dashboard that this PR is showing there. If not let me know.

**Review by krishrahul98 — COMMENTED** [review]
👍🏼

**Pull request merged**
