### PR TITLE
Create reverse_linked_list.java

### PR DESCRIPTION
**Pull request by AnkitaM84**
Java code to reverse a Linked List.
time complexity = O(n)

## Assigned Issue Number?
#81 

## Language Opted?
Java

## Number of files added or updated?
1

## Name of these files?
Data_Structures => LinkedList => Reverse_List => reverse_linked_list.java

### Checklist

- [x] I was assigned for this otherwise my **PR will be rejected**.
- [x] I've read the contribution guidelines.
- [x] I've referred the correct issue number.
- [x] I've filled up this entire template correctly.

:star2: this repository and support.

### CODE REVIEW

**Comment by krishrahul98** [comment]
@AnkitaM84 👍🏼

**Comment by krishrahul98** [comment]
@AnkitaM84 could you please move file to reverse_list folder and then raise pr again. It would be great.

**Comment by AnkitaM84** [comment]
> @AnkitaM84 could you please move file to reverse_list folder and then raise pr again. It would be great.

sure

**Review by krishrahul98 — COMMENTED** [review]
👍🏼

**Pull request merged**
