### PR TITLE
Add SaiKrishna0422 as contributor

### PR DESCRIPTION
**Pull request by SaiKrishna0422**
I made my PR.
I added Sorted Array in java.
Can you please check it once and add hacktoberfest with it?

### CODE REVIEW

**Comment by hemanth-kotagiri** [comment]
@SaiKrishna0422, Please give a reference to your PR so that I can review it.

**Comment by krishrahul98** [comment]
> I made my PR.
> I added Sorted Array in java.
> Can you please check it once and add hacktoberfest with it?

@SaiKrishna0422 if your pr is merged then then it is already qualified for hacktoberfest. Check your hacktoberfest profile.

**Comment by hemanth-kotagiri** [comment]
@krishrahul98, turns out this is his first PR.

**Comment by krishrahul98** [comment]
> @krishrahul98, turns out this is his first PR. He just has a bad title.

@hemanth-kotagiri oh ok.

**Comment by hemanth-kotagiri** [comment]
I don't think this PR demonstrates any algorithm in action which is written from scratch. @SaiKrishna0422, please try implementing Data Structures/Algorithms on your own rather than importing it from the standard library as you did in this PR. Make sure that you read the contribution guidelines as well and please write clean code. Maintain proper indentations.

Looking forward to your new PR. Thanks!

**Review by hemanth-kotagiri — COMMENTED** [review]
Here are a few things you need to take care of while raising your next PR.
1. Always write clean code. Maintain proper indentations and structure your code well.
2. Implement any Data Structures/Algorithms **that are not yet existing in the repository** on your own and raise the PR.
3. You can always contribute to this repository by editing/fixing bugs in already existing files.

**Pull request closed without merging**
